#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Mar 10 21:13:44 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class Invalid(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Invalid.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_1_staticbox = wx.StaticBox(self, -1, "Error")
        self.l_invalid = wx.StaticText(self, -1, "Mail o usuario incorrectos")
        self.b_invalid = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Invalid.__set_properties
        self.SetTitle("Message")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Invalid.__do_layout
        sizer_1 = wx.StaticBoxSizer(self.sizer_1_staticbox, wx.VERTICAL)
        sizer_1.Add(self.l_invalid, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 5)
        sizer_1.Add(self.b_invalid, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Invalid


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    d_invalid = Invalid(None, -1, "")
    app.SetTopWindow(d_invalid)
    d_invalid.Show()
    app.MainLoop()
