import sys
import os

NAME="opentumblr-client"
VERSION = "0.1.0"
DESCRIPTION = "Desktop Client for tumblr"
AUTHOR = "Jair Gaxiola"
AUTHOR_EMAIL = "jyr.gaxiola@gmail.com"
URL = "http://www.opentumblr.com"
LICENSE = "MIT LICENSE"

packages_path = os.path.abspath(os.path.dirname(__file__))
print packages_path
poster = packages_path + '/poster'
simplejson = packages_path + '/simplejson'
opentumblr = packages_path + '/opentumblr'
opentumblr_client = opentumblr + '/opentumblr-client.py'
tumblr = packages_path + '/tumblr.py'

image_files = []

if sys.platform == "darwin":
	"""
	This is a setup.py script generated by py2applet

	Usage:
	    python setup.py py2app --iconfile images/opentumblr.icns
	"""

	from setuptools import setup

	APP = [opentumblr_client]
	path_images = packages_path + '/images/'
	images = ['audiomac.png','chatmac.png','linkmac.png','photomac.png','quotemac.png','textmac.png','videomac.png', 'opentumblr.png']
	for img in images:
		image_files.append(path_images + img)

	DATA_FILES = [('images',image_files)]
	OPTIONS = {'argv_emulation': True}

	setup(
		name=NAME,
		version=VERSION,
		description=DESCRIPTION,
	   	author=AUTHOR,
     	author_email=AUTHOR_EMAIL,
      	url=URL,
      	license=LICENSE,
    	app=APP,
		packages=[poster, simplejson],
	    data_files=DATA_FILES,
	    options={'py2app': OPTIONS},
	    setup_requires=['py2app'],
	)

else:
	if sys.platform == "win32":
		"""
			Usage:
				python setup.py py2exe   
		"""
		
		from distutils.core import setup
		import py2exe
		
		opentumblr_client = opentumblr + '\\opentumblr-client.py'

		path_images = packages_path + '\\images\\'
		images = ['audio.png','chat.png','link.png','photo.png','quote.png','text.png','video.png','audiomac.png','chatmac.png','linkmac.png','photomac.png','quotemac.png','textmac.png','videomac.png','opentumblr.png']
		for img in images:
			image_files.append(path_images + img)

		setup(
			windows=[opentumblr_client],
			data_files=[('images',image_files)],
			options={'py2exe':{'skip_archive':1,'packages':'opentumblr,poster,simplejson'}}
		)
	else:
		from distutils.core import setup
		
		datafiles = []
		doc_files = []
		icon_files = []

		prefix = sys.prefix + '/'

		for arg in sys.argv:
			if arg.startswith('--prefix='):
				prefix = arg[9:]
				prefix = os.path.expandvars(prefix)

		ipath_docs = '%sshare/doc/opentumblr/' % prefix
		ipath_images = '%sshare/pixmaps/opentumblr/' % prefix
		ipath_dashboard = ipath_images+'dashboard/'
		
		path_images = packages_path + '/images/'
		
		images = ['audio.png','chat.png','link.png','photo.png','quote.png','text.png','video.png','audiomac.png','chatmac.png','linkmac.png','photomac.png','quotemac.png','textmac.png','videomac.png','opentumblr.png','opentumblr.xpm']
		for img in images:
			image_files.append(path_images + img)

		docs = ['AUTHORS','INSTALL','LICENSE','README','THANKS']
		for doc in docs:
			doc_files.append(packages_path + '/' + doc)

		if not os.path.isdir(ipath_docs):
			if not os.path.isdir(prefix + 'share'):
				os.mkdir(prefix + 'share')
				os.mkdir(prefix + 'share/doc')
			os.mkdir(ipath_docs)

		if not os.path.isdir(ipath_images):
			if not os.path.isdir(prefix + 'share/pixmaps'):
				os.mkdir(prefix + 'share/pixmaps')
			os.mkdir(ipath_images)
			os.mkdir(ipath_dashboard)
		
		
		datafiles.append((ipath_docs, doc_files))
		datafiles.append(('share/applications',[packages_path+'/opentumblr.desktop']))
		datafiles.append((ipath_dashboard, image_files))

		setup(
			name=NAME,
			version=VERSION,
	      	description=DESCRIPTION,
	      	author=AUTHOR,
	      	author_email=AUTHOR_EMAIL,
	      	url=URL,
	      	license=LICENSE,
	      	scripts=[opentumblr_client],
	      	packages=['opentumblr'],
		    package_dir= {'opentumblr': opentumblr},
            data_files= datafiles
		)
