#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Oct 12 22:52:15 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class Invalid(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Invalid.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.p_main = wx.Panel(self, -1)
        self.sizer_1_copy_staticbox = wx.StaticBox(self.p_main, -1, "Error")
        self.l_invalid = wx.StaticText(self.p_main, -1, "Invalid email or password. Please try again")
        self.b_invalid = wx.Button(self.p_main, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Invalid.__set_properties
        self.SetTitle("Message")
        self.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.p_main.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Invalid.__do_layout
        s_main = wx.BoxSizer(wx.VERTICAL)
        sizer_1_copy = wx.StaticBoxSizer(self.sizer_1_copy_staticbox, wx.VERTICAL)
        sizer_1_copy.Add(self.l_invalid, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 5)
        sizer_1_copy.Add(self.b_invalid, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.p_main.SetSizer(sizer_1_copy)
        s_main.Add(self.p_main, 1, wx.ALL|wx.EXPAND, 10)
        self.SetSizer(s_main)
        s_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Invalid


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    d_invalid = Invalid(None, -1, "")
    app.SetTopWindow(d_invalid)
    d_invalid.Show()
    app.MainLoop()
