#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sun Aug 16 03:55:16 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class AdvancedOptions(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AdvancedOptions.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.l_publishing = wx.StaticText(self, -1, "Publishing options")
        
        """
        Not supported in the tumblr api at this time
        self.cb_publishing = wx.ComboBox(self, -1, choices=["publish now", "add to queue", "publish on...", "save as draft", "private"], style=wx.CB_DROPDOWN)
        """
        
        self.cb_publishing = wx.ComboBox(self, -1, choices=["publish now", "publish on...", "private"], style=wx.CB_DROPDOWN)
        self.l_date = wx.StaticText(self, -1, "Date this post")
        self.tc_date = wx.TextCtrl(self, -1, "")
        self.l_tag = wx.StaticText(self, -1, "Tag this post")
        self.tc_tag = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        
        """
        Not supported in the tumblr api at this time
        self.l_url = wx.StaticText(self, -1, "Set a custom post URL")
        self.tc_url = wx.TextCtrl(self, -1, "/post/123456/")
        """
        self.Bind(wx.EVT_COMBOBOX, self.OnPublishingOptions, id = self.cb_publishing.GetId())
        self.b_ok = wx.Button(self, wx.ID_OK, "")
        self.b_close = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AdvancedOptions.__set_properties
        self.SetTitle("Advanced Options")
        self.cb_publishing.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.cb_publishing.SetSelection(0)
        self.tc_tag.SetMinSize((250, 80))
        self.tc_tag.SetBackgroundColour(wx.Colour(255, 255, 255))
        #self.tc_url.SetFont(wx.Font(13, wx.DECORATIVE, wx.NORMAL, wx.NORMAL, 0, "Lucida Grande"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AdvancedOptions.__do_layout
        s_options = wx.BoxSizer(wx.VERTICAL)
        s_buttons = wx.BoxSizer(wx.HORIZONTAL)
        s_options.Add(self.l_publishing, 0, wx.ALL|wx.EXPAND, 5)
        s_options.Add(self.cb_publishing, 0, wx.ALL|wx.EXPAND, 5)
        s_options.Add(self.l_date, 0, wx.ALL|wx.EXPAND, 5)
        s_options.Add(self.tc_date, 0, wx.ALL|wx.EXPAND, 5)
        s_options.Add(self.l_tag, 0, wx.ALL|wx.EXPAND, 5)
        s_options.Add(self.tc_tag, 0, wx.ALL|wx.EXPAND, 5)
        
        """
        Not supported in the tumblr api at this time
        s_options.Add(self.l_url, 0, wx.ALL|wx.EXPAND, 5)
        s_options.Add(self.tc_url, 0, wx.ALL|wx.EXPAND, 5)
        """
        
        s_buttons.Add(self.b_ok, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        s_buttons.Add(self.b_close, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        s_options.Add(s_buttons, 1, wx.EXPAND, 0)
        self.SetSizer(s_options)
        s_options.Fit(self)
        self.Layout()
        # end wxGlade

    def OnPublishingOptions(self, evt):
        if self.cb_publishing.GetValue() == "add to queue" or self.cb_publishing.GetValue() == "private":
            self.l_date.Show(False)
            self.tc_date.Show(False)
            self.tc_tag.SetFocus()

        if self.cb_publishing.GetValue() == "publish now" or self.cb_publishing.GetValue() == "publish on...":
            if self.cb_publishing.GetValue() == "publish on...":
                self.l_date.SetLabel('Publish time:')
                self.tc_date.SetValue('next tuesday, 10am')
            else:
                self.l_date.SetLabel('Date this post')
                self.tc_date.SetValue('now')

            self.l_date.Show()
            self.tc_date.Show()
            self.tc_date.SetFocus()

        if self.cb_publishing.GetValue() == "save as draft":
            self.l_date.SetLabel('Status message:')
            self.tc_date.SetValue('')
            self.tc_date.Show()
            self.tc_date.SetFocus()
    
# end of class AdvancedOptions