#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Fri Aug 14 15:47:35 2009

import wx
import string
from message import Message
try:
    from opentumblr.tumblr import Api
except ImportError:
    from tumblr import Api
# begin wxGlade: extracode
# end wxGlade



class Quote(wx.Panel):
    def __init__(self, parent, id):
        # begin wxGlade: Quote.__init__
        #kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, parent, id)
        self.parent = parent
        self.api = self.parent.api
        self.s_quote_staticbox = wx.StaticBox(self, -1, "")
        self.l_addquote = wx.StaticText(self, -1, "Add a Quote")
        self.l_quote = wx.StaticText(self, -1, "Quote")
        self.tc_quote = wx.TextCtrl(self, -1, "")
        self.l_source = wx.StaticText(self, -1, "Source ( optional )")
        self.tc_source = wx.TextCtrl(self, -1, "")
        self.b_create = wx.Button(self, -1, "Create post")
        self.b_cancel = wx.Button(self, -1, "Cancel")
        
        self.Bind(wx.EVT_BUTTON, self.OnCreateQuote, id = self.b_create.GetId())
        self.Bind(wx.EVT_BUTTON, self.OnCancel, id = self.b_cancel.GetId())

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Quote.__set_properties
        self.l_addquote.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.l_quote.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.tc_quote.SetMinSize((297, 150))
        self.l_source.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.tc_source.SetMinSize((299, 150))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Quote.__do_layout
        s_quote = wx.StaticBoxSizer(self.s_quote_staticbox, wx.VERTICAL)
        s_buttons = wx.BoxSizer(wx.HORIZONTAL)
        s_quote.Add(self.l_addquote, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
        s_quote.Add(self.l_quote, 0, wx.ALL, 2)
        s_quote.Add(self.tc_quote, 0, wx.ALL|wx.EXPAND, 5)
        s_quote.Add(self.l_source, 0, wx.ALL, 2)
        s_quote.Add(self.tc_source, 0, wx.ALL|wx.EXPAND, 5)
        s_buttons.Add(self.b_create, 0, wx.ALL|wx.EXPAND, 2)
        s_buttons.Add(self.b_cancel, 0, wx.LEFT|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 120)
        s_quote.Add(s_buttons, 0, wx.ALL|wx.EXPAND, 2)
        self.SetSizer(s_quote)
        s_quote.Fit(self)
        # end wxGlade

# end of class Quote
    def OnCreateQuote(self, evt):
    	self.quote = self.tc_quote.GetValue().encode('utf-8')
    	self.source = self.tc_source.GetValue().encode('utf-8')
        self.tags = self.tc_tag.GetValue().encode('utf-8')
        self.tags = string.replace(self.tags,' ', ',')
        self.date = self.tc_date.GetValue().encode('utf-8')

        if self.cb_publishing.GetValue() == 'private':
        	self.private = 1
        else:
        	self.private = 0
        
        if self.quote:
            #self.format = None
            self.api = Api(self.api.name, self.api.email, self.api.password, self.private, self.date, self.tags)
            try:
                self.post = self.api.write_quote(self.quote, self.source)
            except:
                print "posteado en el blog primario"
            self.Close()
        else:
            Message('Quote is required')

    def OnCancel(self, evt):
        self.Close()