#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Fri Aug 14 15:49:11 2009

import wx
import string
from message import Message

try:
    from opentumblr.tumblr import Api
except ImportError:
    from tumblr import Api
# begin wxGlade: extracode
# end wxGlade



class Text(wx.Panel):
    def __init__(self, parent, id):
        # begin wxGlade: Text.__init__
        #kwds["style"] = wx.FULL_REPAINT_ON_RESIZE
        wx.Panel.__init__(self, parent, id)
        self.parent = parent
        self.api = self.parent.api
        self.s_text_staticbox = wx.StaticBox(self, -1, "")
        self.l_text = wx.StaticText(self, -1, "Add a Text Post")
        self.l_title = wx.StaticText(self, -1, "Title (optional)")
        self.tc_title = wx.TextCtrl(self, -1, "")
        self.l_post = wx.StaticText(self, -1, "Post")
        self.tc_post = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.b_create = wx.Button(self, -1, "Create post")
        self.b_cancel = wx.Button(self, -1, "Cancel")
        
        self.Bind(wx.EVT_BUTTON, self.OnCreatePost, id = self.b_create.GetId())
        self.Bind(wx.EVT_BUTTON, self.OnCancel, id = self.b_cancel.GetId())

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Text.__set_properties
        self.l_text.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.l_title.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.l_post.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.tc_post.SetMinSize((310, 250))
        self.b_create.SetFont(wx.Font(13, wx.DECORATIVE, wx.NORMAL, wx.NORMAL, 0, "Lucida Grande"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Text.__do_layout
        s_text = wx.StaticBoxSizer(self.s_text_staticbox, wx.VERTICAL)
        s_buttons = wx.BoxSizer(wx.HORIZONTAL)
        s_text.Add(self.l_text, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
        s_text.Add(self.l_title, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
        s_text.Add(self.tc_title, 0, wx.ALL|wx.EXPAND, 2)
        s_text.Add(self.l_post, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
        s_text.Add(self.tc_post, 0, wx.ALL|wx.EXPAND, 2)
        s_buttons.Add(self.b_create, 0, wx.LEFT|wx.RIGHT, 2)
        s_buttons.Add(self.b_cancel, 0, wx.LEFT|wx.ALIGN_RIGHT, 115)
        s_text.Add(s_buttons, 0, wx.ALL, 5)
        self.SetSizer(s_text)
        s_text.Fit(self)
        # end wxGlade

# end of class Text
    def OnCreatePost(self, evt):
    	self.title = self.tc_title.GetValue().encode('utf-8')
    	self.body = self.tc_post.GetValue().encode('utf-8')
        self.tags = self.tc_tag.GetValue().encode('utf-8')
        self.tags = string.replace(self.tags,' ', ',')
        self.date = self.tc_date.GetValue().encode('utf-8')

        if self.cb_publishing.GetValue() == 'private':
            self.private = 1
        else:
        	self.private = 0
        #print self.cb_publishing.GetValue()
        if self.cb_publishing.GetValue() == 'add to queue':
            self.date = 'on.2'
            
        if self.body:
            #self.format = None
            self.api = Api(self.api.name, self.api.email, self.api.password, self.private, self.date, self.tags)
            try:
                self.post = self.api.write_regular(self.title, self.body)
            except:
                print "Posteado en blog primario"
                #print "Posteado en " % self.post
                #assert False,dir(self.post.values)
            self.Close()
        else:
            Message("Post is required")

    def OnCancel(self, evt):
	    self.Close()