#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Fri Aug 14 15:38:56 2009

import wx

from text import Text
from photo import Photo
from quote import Quote
from link import Link
from chat import Chat
from audio import Audio
from video import Video
# begin wxGlade: extracode
# end wxGlade



class TumbleLog(wx.Panel):
    def __init__(self, parent, id):
        # begin wxGlade: TumbleLog.__init__
        #kwds["style"] = wx.FULL_REPAINT_ON_RESIZE
        wx.Panel.__init__(self, parent, id)
        self.parent = parent
        self.api = self.parent.api
        
        self.panel = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TumbleLog.__set_properties
        self.SetSize((310, 462))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TumbleLog.__do_layout
        self.s_tumblelog = wx.BoxSizer(wx.VERTICAL)
        self.s_tumblelog.Add(self.panel, 1, wx.EXPAND, 0)
        self.SetSizer(self.s_tumblelog)
        # end wxGlade

    def SwitchPanel(self, newpanel):
        self.s_tumblelog.Replace(self.panel, newpanel)
        self.panel.Destroy()
        self.panel = newpanel
        self.Layout()

    def SetPanel(self, paneltype):
        if paneltype == "TEXT":
            newpanel = Text(self, -1)
            self.SwitchPanel(newpanel)
        elif paneltype == "PHOTO":
            newpanel = Photo(self, -1)
            self.SwitchPanel(newpanel)
        elif paneltype == "QUOTE":
            newpanel = Quote(self, -1)
            self.SwitchPanel(newpanel)
        elif paneltype == "LINK":
            newpanel = Link(self, -1)
            self.SwitchPanel(newpanel)
        elif paneltype == "CHAT":
            newpanel = Chat(self, -1)
            self.SwitchPanel(newpanel)
        elif paneltype == "AUDIO":
            newpanel = Audio(self, -1)
            self.SwitchPanel(newpanel)
        elif paneltype == "VIDEO":
            newpanel = Video(self, -1)
            self.SwitchPanel(newpanel)
        else:
            pass
    

# end of class TumbleLog


