#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Fri Aug 14 15:55:45 2009

import wx
import string
from message import Message

try:
    from opentumblr.tumblr import Api
except ImportError:
    from tumblr import Api
# begin wxGlade: extracode
# end wxGlade



class Video(wx.Panel):
    def __init__(self, parent, id):
        # begin wxGlade: Video.__init__
        #kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, parent, id)
        self.parent = parent
        self.api = self.parent.api
        self.s_video_staticbox = wx.StaticBox(self, -1, "")
        self.l_addvideo = wx.StaticText(self, -1, "Add a Video")
        self.l_embed = wx.StaticText(self, -1, "Embed a Video")
        self.label_1 = wx.StaticText(self, -1, "This can be a URL from video sites like YouTube or Vimeo, \nor the raw Embed-tag from any video/flash site. \n(ie. http://youtube.com/watch?v=oCmAD-z7-mA)")
        self.tc_embed = wx.TextCtrl(self, -1, "")
        self.l_caption = wx.StaticText(self, -1, "Caption (optional)")
        self.tc_caption = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.b_create = wx.Button(self, -1, "Create post")
        self.b_cancel = wx.Button(self, -1, "Cancel")
        
        self.Bind(wx.EVT_BUTTON, self.OnCreateVideo, id = self.b_create.GetId())
        self.Bind(wx.EVT_BUTTON, self.OnCancel, id = self.b_cancel.GetId())

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Video.__set_properties
        self.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Lucida Grande"))
        self.l_addvideo.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.l_embed.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_1.SetForegroundColour(wx.Colour(35, 142, 107))
        self.label_1.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Lucida Grande"))
        self.tc_embed.SetMinSize((280, 100))
        self.l_caption.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.tc_caption.SetMinSize((280, 130))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Video.__do_layout
        s_video = wx.StaticBoxSizer(self.s_video_staticbox, wx.VERTICAL)
        s_buttons = wx.BoxSizer(wx.HORIZONTAL)
        s_video.Add(self.l_addvideo, 0, wx.ALL, 2)
        s_video.Add(self.l_embed, 0, wx.ALL, 2)
        s_video.Add(self.label_1, 0, wx.ALL, 2)
        s_video.Add(self.tc_embed, 0, wx.ALL|wx.EXPAND, 10)
        s_video.Add(self.l_caption, 0, wx.ALL, 2)
        s_video.Add(self.tc_caption, 0, wx.ALL|wx.EXPAND, 10)
        s_buttons.Add(self.b_create, 0, wx.ALL|wx.EXPAND, 2)
        s_buttons.Add(self.b_cancel, 0, wx.LEFT|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 135)
        s_video.Add(s_buttons, 0, wx.ALL|wx.EXPAND, 2)
        self.SetSizer(s_video)
        s_video.Fit(self)
        # end wxGlade

# end of class Video
    def OnCreateVideo(self, evt):
    	self.embed = self.tc_embed.GetValue()
    	self.caption = self.tc_caption.GetValue().encode('utf-8')
        self.tags = self.tc_tag.GetValue().encode('utf-8')
        self.tags = string.replace(self.tags,' ', ',')
        self.date = self.tc_date.GetValue().encode('utf-8')

        if self.cb_publishing.GetValue() == 'private':
        	self.private = 1
        else:
        	self.private = 0

        if self.embed:
            #self.format = None
            self.api = Api(self.api.name, self.api.email, self.api.password, self.private, self.date, self.tags)
            try:
                self.post = self.api.write_video(self.embed, self.caption)
            except:
                print "posteado en el blog primario"
            self.Close()
        else:
            Message('Embed a video is required')
            
    def OnCancel(self, evt):
	    self.Close()